//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ServiceModel;

namespace WCF18000
{

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [ServiceContract(CallbackContract = typeof(ICallback), SessionMode = SessionMode.Required)]
    public interface IServer
    {

        [OperationContract(IsOneWay = true)]
        void OTPEncrypt(byte[] data);

        [OperationContract(IsOneWay = true)]
        void OTPDecrypt(byte[] data);

        [OperationContract(IsOneWay = true)]
        void FourSquareEncrypt(string text);

        [OperationContract(IsOneWay = true)]
        void FourSquareDecrypt(string text);

        [OperationContract(IsOneWay = true)]
        void OFBEncrypt(byte[] data);

        [OperationContract(IsOneWay = true)]
        void OFBDecrypt(byte[] data);

        [OperationContract(IsOneWay = true)]
        void XXTEAEncrypt(byte[] data);

        [OperationContract(IsOneWay = true)]
        void XXTEADecrypt(byte[] data);
    }
}
